services:
  redis:
    image: redis
    restart: "no"
    ports:
      - "9000:6379"
    expose:
      - 6379
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    restart: "no"
    ports:
      - "6000:5432"
    expose:
      - 5432
